# Generated by Django 4.1.2 on 2022-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_habitlog_habitlog_unique datelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
