# Generated by Django 4.0.6 on 2022-12-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_alter_habitlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(),
        ),
    ]
