# Generated by Django 4.0.6 on 2022-12-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_alter_habitlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
