# Generated by Django 4.0.6 on 2022-12-20 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_alter_habitlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
