# Generated by Django 4.0.6 on 2022-12-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_alter_habitlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='track_unit',
            field=models.FloatField(default=0),
        ),
    ]
