# Generated by Django 4.0.6 on 2023-02-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0014_alter_habitlog_habit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habitlog',
            name='unique datelog',
        ),
    ]
