# Generated by Django 4.0.6 on 2023-02-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0017_habit_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='semester',
            field=models.CharField(choices=[('', '✅'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.habit'),
        ),
    ]
