# Generated by Django 4.0.6 on 2023-03-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0019_remove_habit_semester_alter_habitlog_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(default='none', max_length=70),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='track_unit',
            field=models.IntegerField(default=0),
        ),
    ]
