# Generated by Django 4.0.6 on 2023-03-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0020_habit_unit_alter_habitlog_track_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(max_length=70),
        ),
    ]
