# Generated by Django 4.0.6 on 2023-03-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0024_remove_habit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(default='none', max_length=70),
        ),
    ]
