# Generated by Django 4.0.6 on 2023-03-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0026_alter_habit_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='unit',
        ),
    ]
