# Generated by Django 4.0.6 on 2023-03-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0028_habit_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='unit',
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_unit',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
