# Generated by Django 4.0.6 on 2023-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0029_remove_habit_unit_habit_goal_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='Confirm_email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
