# Generated by Django 4.0.6 on 2023-03-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0030_remove_profile_email_profile_confirm_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
    ]
