# Generated by Django 4.0.6 on 2023-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0031_remove_habit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(default='', max_length=70),
        ),
    ]
