# Generated by Django 4.0.6 on 2023-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0033_alter_habit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.TextField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default=''),
        ),
    ]
