# Generated by Django 4.0.6 on 2023-03-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0034_alter_habit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='', max_length=100),
        ),
    ]
