# Generated by Django 4.0.6 on 2023-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0036_alter_habit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_unit',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
