# Generated by Django 4.0.6 on 2023-04-07 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0038_profile_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 7)),
        ),
    ]
