# Generated by Django 4.0.6 on 2023-04-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0039_alter_habitlog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='icon',
        ),
    ]
