# Generated by Django 4.0.6 on 2023-04-20 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0040_remove_habit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal_unit',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 20, 13, 26, 4, 813268, tzinfo=utc)),
        ),
    ]
