# Generated by Django 4.0.6 on 2023-04-20 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0041_alter_habit_goal_unit_alter_habitlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 20)),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='habit_track', to='home_app.habit'),
            preserve_default=False,
        ),
    ]
