# Generated by Django 4.0.6 on 2023-04-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0044_alter_habitlog_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
