# Generated by Django 4.1.2 on 2022-10-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
