# Generated by Django 4.0.6 on 2023-03-06 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAddLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('track_unit', models.IntegerField(default=0)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.forumgroups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
