# Generated by Django 4.0.6 on 2023-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_forumaddlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumgroups',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
