# Generated by Django 4.0.6 on 2023-03-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0003_forumgroups_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumaddlog',
            name='track_unit',
            field=models.IntegerField(),
        ),
    ]
