# Generated by Django 4.0.6 on 2023-04-03 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0006_alter_forumgroups_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumgroups',
            name='delete_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
