# Generated by Django 4.0.6 on 2023-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0007_alter_forumgroups_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('desc', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
    ]
